services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports: ["9090:9090"]
    volumes:
      - ./grafana/provisioning/datasources/prometheus.yml:/etc/prometheus/prometheus.yml
    command: ['--config.file=/etc/prometheus/prometheus.yml']
    networks: [obs-net]

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports: ["3000:3000"]
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    depends_on: [prometheus]
    networks: [obs-net]

networks:
  obs-net:
    external: true
    name: obs-net

volumes:
  grafana-storage: {}
