global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'rpc-gateway'
    environment: 'development'

# Alertmanager configuration (for future use)
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets:
#           - alertmanager:9093

# Load rules once and periodically evaluate them
# rule_files:
#   - "alerts/*.yml"

scrape_configs:
  # Kong Gateway metrics
  - job_name: 'kong'
    static_configs:
      - targets: ['kong:8100']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Redis metrics (via redis_exporter if added)
  # - job_name: 'redis'
  #   static_configs:
  #     - targets: ['redis-exporter:9121']

  # PostgreSQL metrics (via postgres_exporter if added)
  # - job_name: 'postgres-app'
  #   static_configs:
  #     - targets: ['postgres-exporter:9187']

  # ClickHouse metrics
  - job_name: 'clickhouse'
    static_configs:
      - targets: ['clickhouse:8123']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Node exporter (system metrics) if added
  # - job_name: 'node'
  #   static_configs:
  #     - targets: ['node-exporter:9100']
