global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: kong
    metrics_path: /metrics
    static_configs:
      - targets: ['kong:8100']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: kong-evm-rpc
